# Generated by Django 4.2.17 on 2025-01-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rushee_name",
                    models.CharField(max_length=150, verbose_name="rushee name"),
                ),
                ("yes_votes", models.IntegerField(verbose_name="yes votes")),
                ("no_votes", models.IntegerField(verbose_name="no votes")),
            ],
        ),
    ]
