# Generated by Django 4.2.17 on 2025-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0003_alter_poll_voters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="rushee_name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="rushee name"
            ),
        ),
    ]
