# Generated by Django 4.2.17 on 2025-03-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0005_poll_idk_votes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"verbose_name": "poll"},
        ),
        migrations.AddField(
            model_name="poll",
            name="vote",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("idk", "Idk")],
                default="no",
                max_length=3,
                verbose_name="vote",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="voter",
            field=models.CharField(
                default="none", max_length=150, verbose_name="voter email"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="poll",
            unique_together={("rushee_name", "voter")},
        ),
        migrations.RemoveField(
            model_name="poll",
            name="idk_votes",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="no_votes",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="voters",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="yes_votes",
        ),
    ]
