# Generated by Django 4.2.17 on 2025-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0006_alter_poll_options_poll_vote_poll_voter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="vote",
            field=models.CharField(max_length=3, verbose_name="vote"),
        ),
    ]
