# Generated by Django 4.2.17 on 2025-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0007_alter_poll_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="rushee_name",
            field=models.CharField(max_length=150, verbose_name="rushee name"),
        ),
    ]
