# Generated by Django 4.2.17 on 2025-08-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0008_alter_poll_rushee_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowIdk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_idk", models.BooleanField(default=False)),
            ],
        ),
    ]
