# Generated by Django 4.2.17 on 2025-08-13 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0009_showidk"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShowIdk",
            new_name="GlobalVariables",
        ),
    ]
