# Generated by Django 4.2.17 on 2025-08-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0010_rename_showidk_globalvariables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalvariables",
            name="show_idk",
        ),
        migrations.AddField(
            model_name="globalvariables",
            name="value",
            field=models.BooleanField(default=False, verbose_name="value"),
        ),
        migrations.AddField(
            model_name="globalvariables",
            name="variable",
            field=models.CharField(
                default="show_idk", unique=True, verbose_name="variable"
            ),
            preserve_default=False,
        ),
    ]
