# Generated by Django 4.2.17 on 2025-08-14 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_loggedinusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grad_year",
            field=models.DateField(
                default=datetime.date.today, verbose_name="grad year"
            ),
        ),
    ]
