# Generated by Django 4.2.17 on 2025-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_customuser_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="grad_year",
            field=models.DateField(blank=True, verbose_name="grad year"),
        ),
    ]
