# Generated by Django 4.2.17 on 2025-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_customuser_email_alter_customuser_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="grad_year",
            field=models.DateField(
                error_messages={"blank": "Graduation Year is required."},
                verbose_name="grad year",
            ),
        ),
    ]
