# Generated by Django 4.2.17 on 2025-08-14 16:08

import datetime
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_customuser_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="grad_year",
            field=models.DateField(
                blank=True,
                default=datetime.date(2025, 8, 14),
                validators=[user.models.date_validator],
                verbose_name="grad year",
            ),
            preserve_default=False,
        ),
    ]
