# Generated by Django 4.2.17 on 2025-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_customuser_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="grad_year",
            field=models.DateField(blank=True, verbose_name="grad year"),
        ),
    ]
