# Generated by Django 4.2.17 on 2025-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_customuser_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
